name: Deploy to GitHub Pages

on:
  push:
    paths:
      - "iclms-website/**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          npm install -g yarn
          cd iclms-website
          yarn install
          yarn build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages  # Replace with your target branch for GitHub Pages
          FOLDER: ./dist  # Replace with the directory that contains your built assets
          CLEAN: true  # Optional: Set to 'true' if you want to clean the target branch before deploying

