name: Continuous Build

on:
  push:
    paths:
      - 'iclms-ui/**'
      - 'iclms-electron/**'
  pull_request:
    paths:
      - 'iclms-ui/**'
      - 'iclms-electron/**'
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-name: CI
          release-name: Continuous Build
          draft: false
          prerelease: true
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Setup node.js
      with:
        uses: actions/setup-node@v4.0.3
        node-version: 21
        cache: yarn
    - name: Build iclms-ui
      run: |
        cd iclms-ui
        yarn install
        yarn build
    - name: Copy files
      run: |
        cd ..
        cp -r iclms-ui/dist/* iclms-electron/serve
    - name: Build electron
      run: |
        cd iclms-electron
        yarn install
        yarn build-linux
    - name: Upload file
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: iclms-electron/dist/iclms-*.tar.gz
        asset_name: iclms-LINUX.tar.gz
        asset_content_type: application/gzip
